oscar:
  host: https://osc.systems/index.php?
  pages:
    shiftlist: c=shift&m=shiftlist&show=50
    shift: c=shift&m=shift&id=
path_feed: public

users:
  - user_1:
    oscar:
      user: user
      pass: pass
    ics:
      - name: GIT
        url: https://host.name/ics/1234

  - user_2:
      ics:
        - name: GIT
          url: https://host.name/ics/2345
